### PR TITLE
[Mono.Debugging.Soft] Invalidate cached local variable values

### PR DESCRIPTION
**Pull request by jstedfast**
This is an attempt to fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109965/

Unfortunately, while this *does* improve things, it doesn't fix the
issue entirely.

### CODE REVIEW

**Comment by jstedfast** [comment]
This fix obsoletes https://github.com/mono/debugger-libs/pull/321

**Comment by mrward** [comment]
How strict are we are not breaking the public API for debugger-libs?

**Comment by jstedfast** [comment]
@mrward that's a good question. I don't know... Maybe @slluis can comment?

**Comment by jstedfast** [comment]
Before breaking API, we should probably at least notify the Unity and XamarinVS teams since I'm not sure if they would be affected by this API break or not.

/cc @jbevain for Unity ?
/cc @joj from XamarinVS ?

**Comment by DavidKarlas** [comment]
I check and neither Unity nor XamarinVS depends on this API... Its unlikely anyone depends on it...

**Comment by netonjm** [comment]
> I check and neither Unity nor XamarinVS depends on this API... Its unlikely anyone depends on it...

Xamarin.IoT uses this library :-)

**Pull request merged**
