### PR TITLE
Minor optimization - check for existence of .pdb before .mdb

### PR DESCRIPTION
**Pull request by nosami**
....as .mdb is deprectated

### CODE REVIEW

**Comment by joj** [comment]
We cannot do this in windows. pdb and mdb always exist side by side, so if we check for pdb first we'll never find mdb.

**Comment by joj** [comment]
Also, we still have a lot of users using mdb in windows because of existing issues with forms that prevent them to migrate to ppdb.

**Comment by joj** [comment]
@jstedfast see my comment before, but also for mdb it's doing (always was) `filename + ".mdb"` and for pdb it's doing `Path.ChangeExtension`, so the logic is ok.

**Comment by jstedfast** [comment]
@joj right, that's what my comment was about - it's consistent with the way the code worked before, but I just thought the naming convention was AssemblyName.dll.pdb but I'm probably wrong :)

That said, if there's a reason we need to prefer mdb over pdb on Windows, then I guess this patch can't go in as-is.

Is there a reason mdb is preferred on Windows? Is it because the pdb and mdb files are inconsistent? e.g. maybe the pdb files are from the Windows-side build and the mdb's are from the Mac-agent portion of the build and are thus inconsistent?

**Comment by joj** [comment]
It's not that we prefer mdb, it's just that this commit in windows completely prevents the usage of mdb, because the pdb will _always_ be there. We do have a lot of users still using mdb.

**Comment by jstedfast** [comment]
Oh, okay.

**Pull request closed without merging**
