### PR TITLE
[soft-debugger-session] Support reloading of mdb files.

### PR DESCRIPTION
**Pull request by lukaszunity**
Solution follows the proposal here: https://github.com/mono/debugger-libs/pull/55

### CODE REVIEW

**Comment by DavidKarlas** [comment]
I like where this is going but I would prefer if
```
readonly Dictionary<string, List<MdbSourceFileInfo>> fileToSourceFileInfos = new Dictionary<string, List<MdbSourceFileInfo>>();
readonly Dictionary<string, List<MdbSourceFileInfo>> mdbToSourceFileInfos = new Dictionary<string, List<MdbSourceFileInfo>>();
```
was replaced with
```
readonly Dictionary<string, Dictionary<string, List<MdbSourceFileInfo>>> mdbsSourceFileInfos = new Dictionary<string, Dictionary<string, List<MdbSourceFileInfo>>>();
```

Where 1st key would represent mdbFilePath.
2nd key would be same logic as now "fileName" and "fullpathFileName".

This would simplify UnloadMdbFile method.

But more importantly I have bad filling about linked files that are shared between projects/.dlls... So I would prefer if fileNames/MdbSourceFileInfo are stored per .mdb instead of somewhat shared between all .mdbs...

**Comment by lukaszunity** [comment]
Thanks for your suggestions, I will take a look and either comment on this PR again or open a new PR.

**Comment by DavidKarlas** [comment]
Also... Please maintain shape orientated programming :D
https://twitter.com/jbevain/status/536497814998908930

**Comment by lukaszunity** [comment]
PR with your suggested changes while maintaining shape oriented programming.

**Comment by DavidKarlas** [comment]
Thank you for this contribution!

**Comment by jstedfast** [comment]
I'm so glad people are amused by my shape oriented programming :)

**Comment by Therzok** [comment]
if shape is trapeze then I agree.

**Pull request merged**
