### PR TITLE
[Mono.Debugging.Soft] Simplified breakpoint resolving logic

### PR DESCRIPTION
**Pull request by jstedfast**
The old logic was trying to be so smart, it smartness-overloaded
into Smartness.MinValue.

In all seriousness, though, now that the IDE intelligently resolves
breakpoints to the correct line, we don't need to be "smart".

This code was only needed 10 years ago when the IDE would put
breakpoints on blank lines and so the debugger would need to
do insanely fuzzy matching. So fuzzy it needed glasses, apparently.

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1094719/

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Difficult to eyeball it from just reading, but I think it makes sense overall.

A few corner cases to think about: 

1. multiple methods covering the same exact span (lambda body inside a method body) - choose the method with the innermost body
2. multiple sequence points on the same line (e.g. `for (int i = 0; i < n; i++)`)
3. multiple methods on the same line ` { get; set; } `

Would it be easy to add a few tests for these scenarios? Or do we not have the proper test infrastructure in this area?

If not, perhaps it's worth it to just create a simple console app with the above scenarios and try it out? Remember to try both debug and release. Release usually gives you less information and you can place breakpoints in less places.

**Comment by DavidKarlas** [comment]
I'm also not convinced breakpoints in `async anonymous` methods will work when placed before debugging starts.

**Comment by DavidKarlas** [comment]
> This is a good chance to add a comprehensive test suite covering breakpoint resolving

Good first step would be re-enabling existing ones: https://github.com/mono/debugger-libs/blob/master/UnitTests/Mono.Debugging.Tests/Shared/BreakpointsAndSteppingTests.cs were disabled here: https://github.com/mono/debugger-libs/pull/306

**Comment by jstedfast** [comment]
@DavidKarlas 

> I'm also not convinced breakpoints in async anonymous methods will work when placed before debugging starts.

You were right, it did not work.

The code works now, though.

**Comment by jstedfast** [comment]
@KirillOsenkov 

> A few corner cases to think about:
> 1. multiple methods covering the same exact span (lambda body inside a method body) - choose the method with the innermost body

This is handled at a higher level by the IDE's BreakpointSpanResolver.

> 2. multiple sequence points on the same line (e.g. for (int i = 0; i < n; i++))

Yep, this is fixed now and there exist unit tests for this (just got all the unit tests passing again).

> 3. multiple methods on the same line { get; set; }

Also works thanks to the IDE's BreakpointSpanResolver and code changes since original PR.

**Comment by slluis** [comment]
@jstedfast So what happened with my request of adding unit tests?

**Comment by Therzok** [comment]
@jstedfast we had tests for that, and they were re-enabled.

**Comment by slluis** [comment]
Re-enabled where?

**Comment by jstedfast** [comment]
@slluis: https://github.com/mono/debugger-libs/blob/master/UnitTests/Mono.Debugging.Tests/Shared/BreakpointsAndSteppingTests.cs#L586

**Pull request merged**
